export { default as BookMarkIcon } from './bookmark.ico'
export { default as ChevronLeftSmIcon } from './chevrons/chevron-left-sm'
export { default as ChevronLeftIcon } from './chevrons/chevron-left.ico'
export { default as ChevronRightSmIcon } from './chevrons/chevron-right-sm'
export { default as ChevronRightWithBgIcon } from './chevrons/chevron-right-with-bg'
export { default as ChevronRightIcon } from './chevrons/chevron-right.ico'
export { default as ClockIcon } from './clock.ico'
export { default as CloseCircleMdIcon } from './close-circle-md.ico'
export { default as AddIcon } from './commons/add.ico'
export { default as CalendarIcon } from './commons/calendar.ico'
export { default as CameraIcon } from './commons/camera.ico'
export { default as CheckRoundIcon } from './commons/check-round.ico'
export { DotIcon, ThreeDotIcon } from './commons/dot.ico'
export { default as TrashImageIcon } from './commons/image-trash.ico'
export { default as LocalizationIcon } from './commons/localization.ico'
export { default as ReportIcon } from './commons/report.ico'
export { default as SwitchAdminIcon } from './commons/switch-admin.ico'
export { default as UnCheckRoundIcon } from './commons/uncheck-round.ico'
export { default as CreditCardIcon } from './dialog-icons/credit-card.ico'
export { default as TrashRedDarkIcon } from './dialog-icons/dark/trash-red-dark.ico'
export { default as ExceedingIcon } from './dialog-icons/exceeding.ico'
export { default as DocumentBlueIcon } from './document-blue.ico'
export { default as Edit05Icon } from './edit-05'
export { default as HeartIcon } from './heart.ico'
export { default as LineDashesIcon } from './line-dashes.ico'
export { default as MoreIcon } from './more'
export { default as PlayIcon } from './play.ico'
export { default as GenogramIcon } from './press-release/genogram.ico'
export { default as PrimaryCheckedIcon } from './primary-checked.ico'
export { default as PrimaryUncheckIcon } from './primary-uncheck.ico'
export { default as RocketIcon } from './rocket.ico'
export { default as ShareProjectIcon } from './share-project.ico'
export { default as SolidTrashIcon } from './solid-trash.ico'
export { default as SignatureIcon } from './startup/signature.ico'
export { default as StampIcon } from './startup/stamp.ico'
export { default as ToolKitIcon } from './startup/toolkit.ico'
export { default as Trash03Icon } from './trash-03'
export { default as UShareIcon } from './u-share'
export { default as VolumeDownIcon } from './volume-down.ico'
export { default as VolumeUpIcon } from './volume-up.ico'

//Home - Business Model
export { default as AddArrowIcon } from './home/business-model/add-arrow.ico'
export { default as AddModelIcon } from './home/business-model/add-model.ico'
export { default as AddRelationIcon } from './home/business-model/add-relation.ico'
export { default as AddingModelIcon } from './home/business-model/adding-model.ico'
export { default as ArrowInformationIcon } from './home/business-model/arrow/information.ico'
export { default as ArrowLightBulbIcon } from './home/business-model/arrow/light-bulb.ico'
export { default as ArrowMoneyIcon } from './home/business-model/arrow/money.ico'
export { default as ArrowOtherIcon } from './home/business-model/arrow/other.ico'
export { default as ArrowProductIcon } from './home/business-model/arrow/product.ico'
export { default as ArrowServiceIcon } from './home/business-model/arrow/service.ico'
export { default as ArrowShareNetworkIcon } from './home/business-model/arrow/share-network.ico'
export { default as ArrowUserIcon } from './home/business-model/arrow/user.ico'
export { default as BuildingIcon } from './home/business-model/building.ico'
export { default as CartIcon } from './home/business-model/cart.ico'
export { default as ChecklistIcon } from './home/business-model/checklist.ico'
export { default as DeleteArrowIcon } from './home/business-model/delete-arrow.ico'
export { default as DeleteIcon } from './home/business-model/delete.ico'
export { default as DonateIcon } from './home/business-model/donate.ico'
export { default as EditArrowIcon } from './home/business-model/edit.ico'
export { default as HorizontalForwardArrowIcon } from './home/business-model/horizontal-forward-arrow.ico'
export { default as HorizontalReverseArrowIcon } from './home/business-model/horizontal-reverse-arrow.ico'
export { default as LocationIcon } from './home/business-model/location.ico'
export { default as NoteIcon } from './home/business-model/note.ico'
export { default as PlusIcon } from './home/business-model/plus.ico'
export { default as ShareIcon } from './home/business-model/share.ico'
export { default as UserPlusIcon } from './home/business-model/user-plus.ico'
export { default as VerticalForwardArrowIcon } from './home/business-model/vertical-forward-arrow.ico'
export { default as VerticalReverseArrowIcon } from './home/business-model/vertical-reverse-arrow.ico'

//Certificate
export { default as ImageIcon } from './certificate/image.ico'
export { default as NumberIcon } from './certificate/number.ico'

//Press release
export { default as MockImageUploadIcon } from './press-release/image-upload.ico'

//Payment management
export { default as CircleInfoIcon } from './payment-management/alert-hexagon.ico'
export { default as ThumbUpIcon } from './payment-management/thumb-up.ico'
