export enum THUMBNAIL_TYPE {
  SQUARE = 'square',
  CIRCLE = 'circle'
}

export enum BOOKMARK_TYPE {
  CONTENT_BLOG = 'CONTENT_BLOG',
  EVENT = 'EVENT',
  PORTFOLIO = 'PORTFOLIO',
  TEAM_BUILDING = 'TEAM_BUILDING',
  MENTORING = 'MENTORING',
  OUTSOURCING_COMPANY = 'OUTSOURCING_COMPANY',
  REFERENCE_ROOM = 'REFERENCE_ROOM',
  CROWDFUNDING = 'CROWDFUNDING',
  QUALIFICATION_TEST = 'QUALIFICATION_TEST',
  STARTUP_TALK = 'STARTUP_TALK',
  COURSE = 'COURSE'
}
