export enum COURSE_QUIZ_TYPE {
  OX = 'OX',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE'
}

export enum COURSE_STATUS {
  ACTIVE = 'ACTIVE',
  DEACTIVATED = 'DEACTIVATED',
  REMOVED = 'REMOVED'
}

export enum COURSE_STATUS_RECRUITMENT {
  WAITING = 'WAITING',
  PROGRESS = 'PROGRESS',
  FINISH = 'FINISH'
}

export enum COURSE_STATUS_APPLY_EXAM {
  WAITING = 'WAITING',
  APPLICANT = 'APPLICANT',
  COMPLETE = 'COMPLETE',
  FAIL = 'FAIL'
}

export enum COURSE_TYPE {
  EDUCATION = 'EDUCATION',
  TEST = 'TEST'
}

export const COURSE_TYPE_OBJECT: Record<string, string> = {
  [COURSE_TYPE.EDUCATION]: '교육+자격시험',
  [COURSE_TYPE.TEST]: '자격시험'
}

export enum COURSE_STUDY_TYPE {
  SEQUENTIAL = 'SEQUENTIAL',
  NON_SEQUENTIAL = 'NON_SEQUENTIAL'
}

export enum COURSE_COMPLETE_TYPE {
  END_OF_COURSE = 'END_OF_COURSE',
  IMMEDIATELY = 'IMMEDIATELY'
}

export enum COURSE_CONTENT_STATUS {
  ACTIVE = 'ACTIVE',
  DEACTIVATED = 'DEACTIVATED',
  REMOVED = 'REMOVED'
}

export enum COURSE_CHAPTER_TYPE {
  CHAPTER = 'CHAPTER',
  ALL = 'ALL'
}

export enum COURSE_QUIZ_TYPE_ORDER {
  DESC = 'DESC',
  ASC = 'ASC',
  RANDOM = 'RANDOM'
}

export enum COURSE_QUIZ_TYPE_QUESTION {
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  OX = 'OX'
}

export enum COURSE_CMS_TYPE {
  VIDEO = 'VIDEO',
  QUIZ = 'QUIZ'
}

export enum COURSE_FILTER_DATE_TYPE {
  APPLICATION = 'APPLICATION',
  REGISTRATION = 'REGISTRATION'
}

export enum COURSE_APPLICATION_OF_USER_FILTER_DATE_TYPE {
  START_TIME = 'START_TIME',
  END_TIME = 'END_TIME'
}

export enum COURSE_APPLICATION_STATUS_RECRUITMENT {
  APPLICANT = 'APPLICANT',
  COMPLETE = 'COMPLETE',
  FAIL = 'FAIL'
}

export enum COURSE_APPLICATION_STATUS_RECRUITMENT_FILTER {
  WAITING = 'WAITING',
  LEARNING = 'LEARNING',
  COMPLETE = 'COMPLETE',
  FAIL = 'FAIL'
}

export enum COURSE_APPLICATION_OF_USER_STATUS_RECRUITMENT_FILTER {
  WAITING = 'WAITING',
  LEARNING = 'LEARNING',
  VERIFICATION = 'VERIFICATION',
  UNCHARGED = 'UNCHARGED',
  COMPLETE = 'COMPLETE'
}

export enum COURSE_APPLICATION_HISTORY_TYPE {
  TEST = 'TEST',
  RETEST = 'RETEST'
}

export enum COURSE_APPLICATION_HISTORY_RESULT {
  PASS = 'PASS',
  FAIL = 'FAIL'
}

export enum COURSE_CERTIFICATION_LIST_TYPE {
  NEWEST = 'NEWEST',
  OLDEST = 'OLDEST'
}

export enum COURSE_EDUCATION_STATUS_RECRUITMENT {
  WAITING = 'WAITING',
  WATCHING = 'WATCHING',
  COMPLETE = 'COMPLETE'
}

export enum STATUS_FORMAT {
  WAITING = 'WAITING',
  PASS = 'PASS',
  FAIL = 'FAIL',
  RETEST = 'RETEST'
}

export enum STATUS_RECRUITMENT_FORMAT {
  TEST = 'TEST', // Not completed all chapter yet + Not taking the test - Check canTest
  RETEST = 'RETEST',
  PASS = 'PASS',
  COMPLETE = 'COMPLETE'
}

export enum TEST_BUTTON_STATE {
  LEARNING = 'LEARNING',
  NOT_TAKE_TEST = 'NOT_TAKE_TEST',
  RETAKE_TEST = 'RETAKE_TEST',
  ISSUE_THE_CERTIFICATE = 'ISSUE_THE_CERTIFICATE',
  COMPLETE = 'COMPLETE'
}

export enum COURSE_FORMAT_STATUS {
  LEARNING = 'LEARNING',
  CAN_TEST = 'CAN_TEST',
  FAIL = 'FAIL',
  FAIL_RETEST = 'FAIL_RETEST',
  PASS = 'PASS',
  COMPLETE = 'COMPLETE',
  RETEST = 'RETEST'
}
