export const KR_LOCALIZATION = {
  CHATS: '채팅',
  WOULD__YOU_LIKE_TO_DELETE_THIS_CONVERSATION: '해당 대화를 삭제하시겠습니까? 해당 대화는 모든 기기에서 삭제됩니다.',
  NO_CHATS_SELECTED: '선택된 채팅 없음',
  DELETE_CONVERSATION: '대화 삭제',
  ADD_TO_CHAT: '채팅에 추가하기',
  NO_CHATS_FOUND: '채팅을 찾을 수 없습니다.',
  CLICK_TO_START_CONVERSATION: '대화를 클릭하여 삭제해 주세요.',
  IN_A_THREAD: '스레드에서',
  MESSAGE_IMAGE: '📷 이미지',
  MESSAGE_FILE: '📁 파일',
  MESSAGE_AUDIO: '🎵 오디오',
  MESSAGE_VIDEO: '📹 비디오',
  CUSTOM_MESSAGE: '메시지가 있습니다.',
  CUSTOM_MESSAGE_POLL: '📊 투표',
  CUSTOM_MESSAGE_STICKER: '💟 스티커',
  CUSTOM_MESSAGE_DOCUMENT: '📃 문서',
  CUSTOM_MESSAGE_WHITEBOARD: '📝 화이트보드',
  USERS: '사용자',
  NO_USERS_FOUND: '사용자를 찾을 수 없습니다.',
  BLOCK_USER: '사용자 차단',
  UNBLOCK_USER: '사용자 차단 해제',
  GROUPS: '그룹',
  NO_GROUPS_FOUND: '그룹을 찾을 수 없습니다.',
  NEW__GROUP: '새 그룹',
  CREATE_GROUP: '그룹 생성',
  ENTER_GROUP_NAME: '그룹 이름 입력',
  PASSWORD: '비밀번호',
  ENTER_GROUP_PASSWORD: '그룹 비밀번호 입력',
  SELECT_GROUP_TYPE: '그룹 유형 선택',
  CONTINUE: '계속',
  GROUP_PASSWORD_BLANK: '그룹 비밀번호는 필수 입력 사항입니다.',
  INVALID_PASSWORD: '유효한 그룹 비밀번호를 입력하고 다시 시도해 주세요.',
  WRONG_PASSWORD: '올바른 비밀번호를 입력하고 다시 시도해 주세요.',
  GROUP_NAME_BLANK: '그룹 이름은 비워 둘 수 없습니다',
  INVALID_GROUP_NAME: '유효한 그룹 이름을 입력하고 다시 시도해 주세요.',
  GROUP_TYPE_BLANK: '그룹 유형은 필수 입력 사항입니다.',
  INVALID_GROUP_TYPE: '유효한 그룹 유형을 입력하고 다시 시도해 주세요.',
  ADMINISTRATOR: '관리자',
  ADMIN: '관리자',
  MODERATOR: '모더레이터',
  PARTICIPANT: '참가자',
  PUBLIC: '공개',
  PRIVATE: '비공개',
  PASSWORD_PROTECTED: '비밀번호로 보호됩니다.',
  PRIVATE_GROUP: '비공개 그룹',
  PROTECTED_GROUP: '보호된 그룹',
  ADD_MEMBERS: '멤버 추가',
  ADDING: '추가 중...',
  DELETE_AND_EXIT: '삭제하고 나가기',
  LEAVE_CONFIRM: '그룹을 나가시겠습니까?',
  LEAVE_GROUP: '그룹 나가기',
  LEAVE: '나가기',
  BANNED_MEMBERS: '차단된 멤버',
  UNBAN: '차단 해제',
  NO_BANNED_MEMBERS_FOUND: '차단된 멤버를 찾을 수 없습니다.',
  VIEW_MEMBERS: '멤버 보기',
  GROUP_MEMBERS: '그룹 멤버',
  KICK: '추방',
  BAN: '차단',
  OWNER: '소유자',
  CHANGE_SCOPE: '범위 변경',
  TRANSFER_OWNERSHIP: '소유권 이전',
  TRANSFER: '이전',
  TRANSFER_CONFIRM: '그룹 소유자입니다. 그룹을 나가기 전에 멤버에게 소유권을 이전해 주세요.',
  JOIN: '가입',
  REMOVE: '제거',
  BLOCK: '차단',
  CHANGE_ROLE: '역할 변경',
  MEMBERS: '멤버',
  MEMBER: '멤버',
  TODAY: '오늘',
  YESTERDAY: '어제',
  SUNDAY: '일요일',
  MONDAY: '월요일',
  TUESDAY: '화요일',
  WEDNESDAY: '수요일',
  THURSDAY: '목요일',
  FRIDAY: '금요일',
  SATURDAY: '토요일',
  TYPING: '입력 중...',
  IS_TYPING: '님이 입력 중...',
  SEND_MESSAGE: '메시지 보내기',
  COPY_MESSAGE: '복사',
  DELETE_MESSAGE: '메시지 삭제',
  EDIT_MESSAGE: '메시지 수정',
  REPLY: '답장',
  REPLIES: '답장',
  LAUNCH: '시작',
  SHARED_COLLABORATIVE_DOCUMENT: '협업 문서를 공유했습니다',
  SHARED_COLLABORATIVE_WHITEBOARD: '협업 화이트보드를 공유했습니다',
  CREATED_WHITEBOARD: '새 협업 화이트보드를 생성했습니다',
  CREATED_DOCUMENT: '새 협업 문서를 생성했습니다.',
  MESSAGE_IS_DELETED: '메시지가 삭제되었습니다.',
  CREATE_POLL: '투표 생성',
  QUESTION: '질문',
  VOTES: '투표',
  VOTE: '투표',
  NO_VOTE: '투표 없습니다.',
  ENTER_YOUR_QUESTION: '질문 입력',
  COLLABORATIVE_DOCUMENT: '협업 문서',
  COLLABORATE_USING_DOCUMENT: '문서를 사용한 협업',
  OPEN_WHITEBOARD: '화이트보드 열기',
  COLLABORATE_USING_WHITEBOARD: '화이트보드를 사용한 협업',
  ADD_REACTION: '반응 추가',
  REACTED: '반응함',
  TRANSLATE_MESSAGE: '메시지 번역',
  TRANSLATED_MESSAGE: '번역된 메시지',
  ATTACH: '첨부',
  ATTACH_FILE: '파일 첨부',
  ATTACH_AUDIO: '오디오 첨부',
  ATTACH_VIDEO: '비디오 첨부',
  ATTACH_IMAGE: '이미지 첨부',
  EMOJI: '이모지',
  ENTER_YOUR_MESSAGE_HERE: '여기에 메시지를 입력해 주세요',
  NO_MESSAGES_FOUND: '메시지를 찾을 수 없음',
  THREAD: '스레드',
  REPLY_TO_THREAD: '스레드에 답장하기',
  REPLY_IN_THREAD: '스레드에서 답장하기',
  VIEW: '보기',
  VIEW_DETAIL: '세부 정보 보기',
  LIVE_REACTION: '라이브 반응',
  JUMP: '점프',
  NEW_MESSAGES: '새 메시지',
  NEW_MESSAGE: '새 메시지',
  CALLS: '통화',
  CALL_DETAILS: '통화 세부 정보',
  MISSED_VOICE_CALL: '부재중 음성 통화',
  MISSED_VIDEO_CALL: '부재중 비디오 통화',
  INCOMING_AUDIO_CALL: '수신 오디오 통화',
  DECLINE: '거절',
  ACCEPT: '수락',
  CALL_INITIATED: '통화 시작됨',
  OUTGOING_AUDIO_CALL: '발신 오디오',
  OUTGOING_VIDEO_CALL: '발신 비디오 통화',
  CALL_REJECTED: '통화 거절됨',
  REJECTED_CALL: '거절된 통화',
  CALL_ACCEPTED: '통화 수락됨',
  OUTGOING_CALL: '발신 통화',
  INCOMING_CALL: '수신 통화',
  MISSED_CALL: '부재중 통화',
  MISSED_AUDIO_CALL: '부재중 오디오 통화',
  JOINED: '참여함',
  CALL_ENDED: '통화 종료됨',
  CALL_CANCELLED: '통화 취소됨',
  CALLING: '통화 중...',
  SELECT_VIDEO_SOURCE: '비디오 소스 선택',
  SELECT_INPUT_AUDIO_SOURCE: '입력 오디오 소스 선택',
  SELECT_OUTPUT_AUDIO_SOURCE: '출력 오디오 소스 선택',
  INITIATED_GROUP_CALL: '그룹 통화 시작됨',
  YOU_INITIATED_GROUP_CALL: '그룹 통화를 시작했습니다',
  RESIZE: '크기 조정',
  LOADING: '로딩 중...',
  SEARCH: '검색',
  ERROR: '오류'
}

export const ERRORS = new Set(['ERR_UID_NOT_FOUND'])
