export enum APPLICATION_PROGRESS {
  ALL = '',
  APPROVAL = 'APPROVAL',
  IN_PROCESS = 'IN_PROCESS',
  WRITE_REPORT = 'WRITE_REPORT',
  COMPLETE = 'COMPLETE',
  CANCELED = 'CANCELED',
  REVIEW = 'REVIEW',
  PENDING = 'PENDING'
}

export const MENTORING_PROGRESS_LIST_TABS = [
  { value: APPLICATION_PROGRESS.ALL, label: '전체' },
  { value: APPLICATION_PROGRESS.PENDING, label: '신청' },
  { value: APPLICATION_PROGRESS.IN_PROCESS, label: '진행' },
  { value: APPLICATION_PROGRESS.COMPLETE, label: '완료' },
  { value: APPLICATION_PROGRESS.WRITE_REPORT, label: '보고서 작성' }
]

export const MENTEE_PROGRESS_LIST_TABS = [
  { value: APPLICATION_PROGRESS.ALL, label: '전체' },
  { value: APPLICATION_PROGRESS.APPROVAL, label: '신청' },
  { value: APPLICATION_PROGRESS.IN_PROCESS, label: '진행' },
  { value: APPLICATION_PROGRESS.COMPLETE, label: '완료' },
  { value: APPLICATION_PROGRESS.REVIEW, label: '리뷰' }
]

export enum BOOKMARK_TYPE {
  CONTENT_BLOG = 'CONTENT_BLOG',
  EVENT = 'EVENT',
  PORTFOLIO = 'PORTFOLIO',
  TEAM_BUILDING = 'TEAM_BUILDING',
  MENTORING = 'MENTORING',
  OUTSOURCING_COMPANY = 'OUTSOURCING_COMPANY',
  REFERENCE_ROOM = 'REFERENCE_ROOM',
  CROWDFUNDING = 'CROWDFUNDING',
  QUALIFICATION_TEST = 'QUALIFICATION_TEST'
}

export enum MENTOR_PRODUCT_TYPE {
  TWENTY_MINUTES = 'TWENTY_MINUTES',
  FORTY_MINUTES = 'FORTY_MINUTES',
  AN_HOUR = 'AN_HOUR'
}

export enum MANAGE_TYPE {
  MENTEE = 'mentee',
  MENTOR = 'mentor'
}
export enum MENTOR_TRANSACTION_STATUS {
  PENDING = 'PENDING',
  COMPLETE = 'COMPLETE',
  CANCELED = 'CANCELED'
}

export const status = ['PENDING', 'APPROVAL', 'COMPLETE', 'IN_PROCESS', 'CANCELED', 'WRITE_REPORT']
