export enum ORDER_STATUS {
  ACTIVE = 'ACTIVE', //SUCCESS
  REMOVED = 'REMOVED',
  PENDING = 'PENDING',
  FAILED = 'FAILED',
  CANCELED = 'CANCELED',
  COMPLETE = 'COMPLETE'
}

export enum ORDER_TYPE {
  USER = 'USER',
  CONTENT = 'CONTENT',
  EVENT = 'EVENT',
  STARTUP_TALK = 'STARTUP_TALK'
}
