export enum REPORT_CATEGORY {
  COMMERCIAL_PROMOTIONAL = 1, //"영리목적/홍보성",
  ILLEGAL_INFORMATION = 2, // "불법정보",
  PROFANITY_PERSONAL_ATTACK = 3, // "욕설/인신공격",
  REPETITIVE_CONTENT = 4, //"같은 내용 반복(도배)",
  PERSONAL_INFORMATION_EXPOSURE = 5, // "개인정보 노출",
  OBSCENITY_SEXUALITY = 6, //"음란성/선정성",
  ACCOUNT_DB_TRANSACTION = 7, //"아이디/DB거래",
  OTHER = 8 //"기타",
}

export const REPORT_CATEGORY_LABEL = new Map([
  [[REPORT_CATEGORY.COMMERCIAL_PROMOTIONAL], '영리목적/홍보성'],
  [[REPORT_CATEGORY.PERSONAL_INFORMATION_EXPOSURE], '개인정보 노출'],
  [[REPORT_CATEGORY.ILLEGAL_INFORMATION], '불법정보'],
  [[REPORT_CATEGORY.OBSCENITY_SEXUALITY], '음란성/선정성'],
  [[REPORT_CATEGORY.PROFANITY_PERSONAL_ATTACK], '욕설/인신공격'],
  [[REPORT_CATEGORY.ACCOUNT_DB_TRANSACTION], '아이디/DB거래'],
  [[REPORT_CATEGORY.REPETITIVE_CONTENT], '같은 내용 반복(도배)'],
  [[REPORT_CATEGORY.OTHER], '기타']
])

export enum REPORT_TYPE {
  POST = 'POST',
  COMMENT = 'COMMENT',
  ACCOUNT = 'ACCOUNT',
  CHALLENGE = 'CHALLENGE',
  CONTENT = 'CONTENT',
  CONTENT_BLOG = 'CONTENT_BLOG',
  STARTUP_TALK = 'STARTUP_TALK',
  MENTORING = 'MENTORING',
  MENTORING_REVIEW = 'MENTORING_REVIEW',
  PROJECT = 'PROJECT',
  EVENT = 'EVENT',
  PORTFOLIO = 'PORTFOLIO',
  TEAM_BUILDING = 'TEAM_BUILDING',
  OUTSOURCING_COMPANY = 'OUTSOURCING_COMPANY',
  REFERENCE_ROOM = 'REFERENCE_ROOM',
  CROWDFUNDING = 'CROWDFUNDING',
  QUALIFICATION_TEST = 'QUALIFICATION_TEST'
}
