export const MAXLENGTH_INPUT = {
  INDUSTRY: 20,
  IDEA: 50,
  SELECTED_COMPETITORS: 4,
  SEARCH_COMPETITORS: 20,
  COMPANY_NAME: 20,
  COMPANY_DESC: 100,
  COMPANY_HOMEPAGE: 100,
  KEYWORDS_TEXT: 10,
  KEYWORDS: 6,
  SELECTED_CHARACTERISTICS: 3,
  SELECTED_COMPARISON_COMPETITORS: 7,
  SELECTED_COMPARISON_COMPETITORS_TEXT: 50
}

export const TAB_VALUE_TYPE = [
  {
    id: 'KOREAN',
    name: '한국기업'
  },
  {
    id: 'GLOBAL',
    name: '글로벌기업'
  }
]

export const FIELD_TYPE = {
  TARGET_CUSTOMER: 'TARGET_CUSTOMER',
  DIFFERENT_CHARACTERISTICS: 'DIFFERENT_CHARACTERISTICS',
  TEXT: 'TEXT',
  OPTION: 'OPTION',
  SLIDE: 'SLIDE',
  SELECT_STRUCTURE: 'SELECT_STRUCTURE',
  SELECT_PROMOTION: 'SELECT_PROMOTION'
}
