export const MAX_ITEM_ORGANIZATION = 10
export const MAX_ITEM_PERSON_HOST = 3
export const MAX_ITEM_PERSON_MEMBER = 5

const WIDTH_ROW = 200

export const EDITOR = {
  WIDTH_TABLE: WIDTH_ROW,
  HEIGHT_TABLE: WIDTH_ROW / 6.5
}

export enum EventNameTBuidlding {
  RESET_TBUIDLING_ST3 = 'RESET_TBUIDLING_ST3',
  RESET_TBUIDLING_ST4 = 'RESET_TBUIDLING_ST4',
  TOGGLE_TAB_VIEW_TREE = 'TOGGLE_TAB_VIEW_TREE',
  CHANGE_COLOR_TOOLBAR = 'CHANGE_COLOR_TOOLBAR',
  CLEAR_ERROR_MSG = 'CLEAR_ERROR_MSG'
}

export enum TEAMBUILDING_QUERY_KEY {
  TEAM_BUILDING_ALL_ACTIVE_STEP = 'TEAM_BUILDING_ALL_ACTIVE_STEP',
  GET_DATA_S1 = 'GET_DATA_S1',
  GET_DATA_S2 = 'GET_DATA_S2',
  GET_DATA_S3 = 'GET_DATA_S3',
  GET_DATA_S4 = 'GET_DATA_S4'
}

export const EDGE_DOT = 10;