import { MENTOR_PRODUCT_TYPE } from '../mentor.constant'

export enum MENTORING_STATUS {
  PENDING = 'PENDING',
  APPROVAL = 'APPROVAL',
  REMOVED = 'REMOVED',
  REJECTED = 'REJECTED'
}

export enum MENTORING_BADGE {
  RECOMMEND = 'RECOMMEND',
  BEST_OF_MONTH = 'BEST_OF_MONTH',
  BEST_OF_REVIEW = 'BEST_OF_REVIEW'
}

export const MENTORING_COURSE_NAME = new Map([
  [MENTOR_PRODUCT_TYPE.TWENTY_MINUTES, '20분 화상 멘토링'],
  [MENTOR_PRODUCT_TYPE.FORTY_MINUTES, '40분 화상 멘토링'],
  [MENTOR_PRODUCT_TYPE.AN_HOUR, '1시간 대면 멘토링']
])
